sudo: required

language: bash

services:
  - docker

before_install:
    - docker pull vect0r/nginx-openssl1.0.2
    - docker build -t vect0r/nginx-openssl1.0.2 .
    - docker run -d -p 127.0.0.1:80:80 vect0r/nginx-openssl1.0.2
    - docker ps -a | /usr/bin/awk '{print $1}'

script:
    - docker exec -it $(!!) /usr/bin/pgrep -F /var/run/nginx.pid
